---

- debug:
    var: debug

- set_fact:
    testPassed: false

# Do Not send commands that modify anything !
- debug:
    msg: "Send Command Received.. {{ command }}"
  when: "{{debug==true}}"

- name: "Send Test Command {{ command }}"
  command: "{{ command}}"
  register: result
  ignore_errors: true


- debug:
    var: result
  when: "{{debug==true}}"

- name: Include Command OK Logic if rc==0 (no command error)
  include: rc0.yml
  when: result.rc == 0

- name: Include Command not OK rc!=0 (command error)
  include: rc_not_0.yml
  when: result.rc != 0

- debug:
    var: testPassed
  when: "{{debug==true}}"

- debug:
    msg: "TEST_PASSED: with command {{ command }},  expected {{ expected }} "
  when:
    - testPassed == true

# failed tests either debug a failed message or fail immediately (as requested by the calling _test playbook

- debug:
    msg: "TEST_FAILED: with command {{ command }},  expected {{ expected }}  "
  when:
    - testPassed == false

- fail:
    msg: "TEST_FAILED: with command {{ command }},  expected {{ expected }}  "
  when:
    - testPassed == false
    - immediate_exit_on_fail == true

